// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SFT.Core.Data;

#nullable disable

namespace SFT.Core.Data.Migrations
{
    [DbContext(typeof(SatisfactoryDbContext))]
    [Migration("20260222043341_AddMinerMkAndNodePurity")]
    partial class AddMinerMkAndNodePurity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SFT.Core.Domain.Factory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Factories");
                });

            modelBuilder.Entity("SFT.Core.Domain.FactoryInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPerMinute")
                        .HasColumnType("numeric");

                    b.Property<int>("FactoryLevelId")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer");

                    b.Property<int?>("SourceFactoryLevelId")
                        .HasColumnType("integer");

                    b.Property<int?>("SourceMineId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("SourceFactoryLevelId");

                    b.HasIndex("SourceMineId");

                    b.HasIndex("FactoryLevelId", "ResourceId")
                        .IsUnique();

                    b.ToTable("FactoryInputs", t =>
                        {
                            t.HasCheckConstraint("CK_FactoryInputs_Source", "(\"SourceMineId\" IS NULL) <> (\"SourceFactoryLevelId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("SFT.Core.Domain.FactoryLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FactoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId", "Identifier")
                        .IsUnique();

                    b.ToTable("FactoryLevels");
                });

            modelBuilder.Entity("SFT.Core.Domain.FactoryOutput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPerMinute")
                        .HasColumnType("numeric");

                    b.Property<int>("FactoryLevelId")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("FactoryLevelId", "ResourceId")
                        .IsUnique();

                    b.ToTable("FactoryOutputs");
                });

            modelBuilder.Entity("SFT.Core.Domain.Mine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NodePurity")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("Mines");
                });

            modelBuilder.Entity("SFT.Core.Domain.MineOutput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPerMinute")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InputAmountPerMinute")
                        .HasColumnType("numeric");

                    b.Property<int>("MineId")
                        .HasColumnType("integer");

                    b.Property<string>("RecipeKeyName")
                        .HasColumnType("text");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("MineId", "ResourceId")
                        .IsUnique();

                    b.ToTable("MineOutputs");
                });

            modelBuilder.Entity("SFT.Core.Domain.MiningStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MineId")
                        .HasColumnType("integer");

                    b.Property<int>("MinerMk")
                        .HasColumnType("integer");

                    b.Property<int>("OverclockLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MineId", "MinerMk", "OverclockLevel")
                        .IsUnique();

                    b.ToTable("MiningStations");
                });

            modelBuilder.Entity("SFT.Core.Domain.ProductionRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CraftTimeSeconds")
                        .HasColumnType("numeric");

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KeyName")
                        .IsUnique();

                    b.ToTable("ProductionRecipes");
                });

            modelBuilder.Entity("SFT.Core.Domain.ProductionRecipeResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsInput")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductionRecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("ProductionRecipeId", "ResourceId", "IsInput");

                    b.ToTable("ProductionRecipeResources");
                });

            modelBuilder.Entity("SFT.Core.Domain.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KeyName")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("SFT.Core.Domain.FactoryInput", b =>
                {
                    b.HasOne("SFT.Core.Domain.FactoryLevel", "FactoryLevel")
                        .WithMany("Inputs")
                        .HasForeignKey("FactoryLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFT.Core.Domain.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SFT.Core.Domain.FactoryLevel", "SourceFactoryLevel")
                        .WithMany()
                        .HasForeignKey("SourceFactoryLevelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SFT.Core.Domain.Mine", "SourceMine")
                        .WithMany()
                        .HasForeignKey("SourceMineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FactoryLevel");

                    b.Navigation("Resource");

                    b.Navigation("SourceFactoryLevel");

                    b.Navigation("SourceMine");
                });

            modelBuilder.Entity("SFT.Core.Domain.FactoryLevel", b =>
                {
                    b.HasOne("SFT.Core.Domain.Factory", "Factory")
                        .WithMany("Levels")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factory");
                });

            modelBuilder.Entity("SFT.Core.Domain.FactoryOutput", b =>
                {
                    b.HasOne("SFT.Core.Domain.FactoryLevel", "FactoryLevel")
                        .WithMany("Outputs")
                        .HasForeignKey("FactoryLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFT.Core.Domain.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FactoryLevel");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("SFT.Core.Domain.Mine", b =>
                {
                    b.HasOne("SFT.Core.Domain.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("SFT.Core.Domain.MineOutput", b =>
                {
                    b.HasOne("SFT.Core.Domain.Mine", "Mine")
                        .WithMany("Outputs")
                        .HasForeignKey("MineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFT.Core.Domain.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mine");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("SFT.Core.Domain.MiningStation", b =>
                {
                    b.HasOne("SFT.Core.Domain.Mine", "Mine")
                        .WithMany("MiningStations")
                        .HasForeignKey("MineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mine");
                });

            modelBuilder.Entity("SFT.Core.Domain.ProductionRecipeResource", b =>
                {
                    b.HasOne("SFT.Core.Domain.ProductionRecipe", "ProductionRecipe")
                        .WithMany("Resources")
                        .HasForeignKey("ProductionRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFT.Core.Domain.Resource", "Resource")
                        .WithMany("RecipeUsages")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionRecipe");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("SFT.Core.Domain.Factory", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("SFT.Core.Domain.FactoryLevel", b =>
                {
                    b.Navigation("Inputs");

                    b.Navigation("Outputs");
                });

            modelBuilder.Entity("SFT.Core.Domain.Mine", b =>
                {
                    b.Navigation("MiningStations");

                    b.Navigation("Outputs");
                });

            modelBuilder.Entity("SFT.Core.Domain.ProductionRecipe", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("SFT.Core.Domain.Resource", b =>
                {
                    b.Navigation("RecipeUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
